name: dfpl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build=3.21.8
  - conda=4.12.0
  - matplotlib=3.5.1
  - numpy=1.19.5
  - pandas=1.4.2
  - pip=22.0.4
  - pytest=7.1.1
  - rdkit=2022.03.1
  - scikit-learn=1.0.2
  - tensorflow-gpu=2.6.0
  - wandb=0.12.11
