name: Push changes to Gitlab
on:
  push:
    branches:
      - main
      - master
  release:
    types: [released]

jobs:
  sync_to_hzdr:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.repository.default_branch }}'
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add hzdr https://SYNC_FROM_GITHUB:${{ secrets.HZDR_ACCESS_TOKEN }}@gitlab.hzdr.de/department-computational-biology/deepfplearn.git
          git remote -v
          git push --tags hzdr "${{ github.event.repository.default_branch }}"
