# workflow adapted from
# https://github.com/singularityhub/github-ci
name: Singularity Build (docker)
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.6.2'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      env:
        SINGULARITY_RECIPE: singularity_container/conda_rdkit2019.def
        OUTPUT_CONTAINER: deepFPlearn.sif
      run: |
       python setup.py bdist_wheel -d singularity_container
       ls
       if [ -f "${SINGULARITY_RECIPE}" ]; then
           cd $(dirname ${SINGULARITY_RECIPE})
           singularity build ${OUTPUT_CONTAINER} $(basename ${SINGULARITY_RECIPE})
           echo "${SINGULARITY_RECIPE} built successfully"
           ls -la 
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi
